### ISSUE TITLE
Error on gulp

### ISSUE THREAD

**Issue by honghuamin** [amazeui/amt-starter-kit#1]
when run gulp command , it show error:

[18:12:24] Requiring external module babel-core/register
module.js:339
    throw err;
    ^

Error: Cannot find module 'babel-preset-stage-1'
...

**Comment by minwe** [comment]
你自己在 babel 设置里加的 `stage-1` 吧？

http://babeljs.io/docs/plugins/preset-stage-1/

**Comment by honghuamin** [comment]
没动过.babelrc文件。检查过这个文件，里面是
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread",
    "transform-object-assign"
  ]
}

倒是在用amaze之前，有安装过babel，应该相互不影响嘛

**Comment by minwe** [comment]
你把目录下面的 `node_modules` 删了，重新执行 `npm install` 试试。

报错是说没有安装 `babel-preset-stage-1` 这个模块，这个模块如果没有改过配置的话是没用到的。

我这边没有报错。

**Comment by honghuamin** [comment]
升级到nodejs 5以后不再报错
