### ISSUE TITLE
页面传值问题是怎么解决的

### ISSUE THREAD

**Issue by xudao520** [amazeui/amt-starter-kit#11]
![image](https://cloud.githubusercontent.com/assets/12093709/16371988/909b1014-3c7c-11e6-8e07-89a80558e6fd.png)
比如这张图想要传多个参数怎么传的

**Comment by xudao520** [comment]
@minwe

**Comment by minwe** [comment]
https://github.com/reactjs/react-router/blob/master/docs/API.md#to

可以用 `query` 传过去吧。

**Comment by xudao520** [comment]
貌似用to带query传过去直接报不匹配router的错误 @minwe

**Comment by minwe** [comment]
https://github.com/amazeui/amt-starter-kit/blob/232a935299b4d7510ba2d718b00e491ae71d96c2/app/js/pages/Index.js#L29

**Comment by xudao520** [comment]
@minwe 好的，谢谢

**Comment by xudao520** [comment]
还有一个问题就是query传过去是通过什么获取的，是自己用正则截取？ @minwe

**Comment by minwe** [comment]
https://github.com/amazeui/amt-starter-kit/commit/232a935299b4d7510ba2d718b00e491ae71d96c2 看另外那个文件新加的代码。

**Comment by xudao520** [comment]
一直在page2里面获取难怪获取不到
![image](https://cloud.githubusercontent.com/assets/12093709/16375626/df5f49b0-3c8e-11e6-8216-853067d4106a.png)，谢谢了

**Comment by minwe** [comment]
多翻翻 React Router 的文档，里面其实会涉及其他获取方法的。
