### ISSUE TITLE
amt-starter-kit 环境跑不起来。

### ISSUE THREAD

**Issue by SendLessLove** [amazeui/amt-starter-kit#14]
我运行的时候说找不到dist文件夹，然后3000端口的页面上显示 “Cannot GET /”
求解决办法。

**Comment by kdenz** [comment]
@SendLessLove 我试过是可以的，重新clone 完试一下？

**Comment by liuyq1step** [comment]
@kdenz 同样的问题

**Comment by kdenz** [comment]
@SendLessLove @liuyq1step 錯誤信息是什麼？

**Comment by liuyq1step** [comment]
@kdenz 第一次没看console。删掉再次npm install ，错误在node-sass build.js失败。再次npm install成功。
