### ISSUE TITLE
依赖的项目太多了 能不能少点

### ISSUE THREAD

**Issue by yay2008** [amazeui/amt-starter-kit#2]
安装了几次都不成功 node-gyp这个还得安装个11g的 Visual C++,搞前端开发 弄的这么麻烦

**Comment by minwe** [comment]
这个没办法，就像使用 Mac 也要安装 Xcode 一样。

虽然是前端开发，但是基于 Node.js 开发的很多工具，编译环境是为工具做准备的。

比起工具这些工具带来的效率提升，最初的环境配置麻烦一点还是值得的。
