### ISSUE TITLE
I get the issue in win7. please help me. Thanks

### ISSUE THREAD

**Issue by zhuzhengwen1983** [amazeui/amt-starter-kit#4]
![image](https://cloud.githubusercontent.com/assets/846381/11889115/53c81e90-a580-11e5-9769-c3097624643c.png)

**Comment by minwe** [comment]
https://github.com/amazeui/amt-starter-kit/issues/3#issuecomment-162433893

**Comment by zhuzhengwen1983** [comment]
app/js/app.js
22:8 error Parsing error: Unexpected token ..

app.js 里面是不是有error，如何修改正确啊？

**Comment by minwe** [comment]
确保项目目录下面有 `.babelrc` 这个文件。

**Comment by zhuzhengwen1983** [comment]
我QQ是12664357， 我的项目下面有您提到的.babelrc
![image](https://cloud.githubusercontent.com/assets/846381/11892865/e2e5c7d2-a5a6-11e5-87a8-2a5e4e525f83.png)

**Comment by minwe** [comment]
https://www.teamviewer.com/zhCN/index.aspx 安装 TeamViewer 以后给我 ID 和密码

**Comment by minwe** [comment]
```
app/js/app.js
  22:8  error  Parsing error: Unexpected token ..
```

这个也是 ESLint 的提示信息，不用管他。正常编写就行了。

**Comment by zhuzhengwen1983** [comment]
好的，谢谢
