### ISSUE TITLE
npm ERR! peerinvalid The package eslint does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by zaozaool** [amazeui/amt-starter-kit#5]
在执行npm install时发生错误，前面都正常，请问是什么原因？

gyp info ok 
Installed in ` /home/vagrant/repo/amt-starter-kit/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-ia32-14/binding.node `
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2

npm ERR! shasum check failed for /tmp/npm-1738-2fcaafe5/registry.npmjs.org/weinre/-/weinre-2.0.0-pre-I0Z7U9OV.tgz
npm ERR! Expected: fef8aa223921f7b40bbbbd4c3ed4302f6fd0a813
npm ERR! Actual:   7c7e19082d78b80fe16a646735a9ce234e6ecbb6
npm ERR! From:     https://registry.npmjs.org/weinre/-/weinre-2.0.0-pre-I0Z7U9OV.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/repo/amt-starter-kit/npm-debug.log

 
 

vagrant@precise32:~/repo/amt-starter-kit$ npm install
npm WARN optional dep failed, continuing fsevents@1.0.11
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint does not satisfy its siblings' peerDependencies requirements!

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/repo/amt-starter-kit/npm-debug.log

**Comment by minwe** [comment]
貌似也有人遇到过这样的问题：

https://github.com/yannickcr/eslint-plugin-react/issues/154

你升级一下 Node 版本吧，4.4.2，NPM 升级到 2.x 最新版本试试。
