### ISSUE TITLE
快速上手套件运行时报错，所有链接无法跳转

### ISSUE THREAD

**Issue by wy54600316** [amazeui/amt-starter-kit#6]
如标题描述，npm start启动之后控制台报错：
Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

工程目录下执行npm ls react，出现的结果是：
├─┬ amazeui-touch@0.1.0-beta2
│ └── react@15.0.1
└── react@0.14.8

请问该如何解决呢？

**Comment by minwe** [comment]
手动把 `node_modules/amazeui-touch/node_modules` 下面的 `react` 删掉，重新执行 `npm start` 应该就没问题了。

**Comment by wy54600316** [comment]
问题已解决。
