### ISSUE TITLE
Apr 11, 2016的依赖版本更新引发控制台报错

### ISSUE THREAD

**Issue by wy54600316** [amazeui/amt-starter-kit#7]
4月11号更新的react和react-dom依赖版本从0.14.7替换成最新的15.0.1，会引发控制台报错：
Warning: Element: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
把react版本还原之后错误消失，启用最新版本此处不知是否要更新写法？

**Comment by minwe** [comment]
这个警告信息你可以先忽略，可以使用 `15.0.1`，不影响程序运行。

我们后续会处理。
