### ISSUE TITLE
app.js 20行代码异常

### ISSUE THREAD

**Issue by coderjiang2013** [amazeui/amt-starter-kit#8]
我在项目中使用TabBar组件作为底部按钮，借鉴了app.js的写法，但在20行的赋值代码报错，刚刚接触 touch 和 react， 希望可以得到帮助

`        const {
            location,
            params,
            children,
            ...props,
            } = this.props;`
![err](https://cloud.githubusercontent.com/assets/4484149/15797338/b53d8952-29d9-11e6-9093-674385747150.png)

**Comment by minwe** [comment]
https://babeljs.io/docs/plugins/transform-object-rest-spread/
